### ISSUE TITLE
本地搭建完之后访问域名报错

### ISSUE THREAD

**Issue by wx244959547** [higress-group/higress-group.github.io#140]
本地按照https://higress.io/zh-cn/docs/user/quickstart 搭建后 访问http://console.higress.io/ 显示报错 
no healthy upstream

**Comment by CH3CHO** [comment]
检查一下相关组件是否都正常启动了：`kubectl get po -n higress-system`

**Comment by CH3CHO** [comment]
Close due to inactivity.
