### ISSUE TITLE
higress-core.gateway.hostNetwork  true 不知道具体怎么配置

### ISSUE THREAD

**Issue by camuselliot** [higress-group/higress-group.github.io#229]
想配置这个higress-core.gateway.hostNetwork  true
 不知道怎么配置 
老师能具体给命令演示一下吗 
https://higress.cn/zh-cn/docs/user/configurations/ 
以下运维参数，可以通过 helm 命令的 --set 或者 --values 方式进行设置，也可以通过 hgctl 的 profile 文件中的 values 字段来实现控制
这个问了一圈的人都不知道咋弄

**Comment by CH3CHO** [comment]
以“[快速开始](https://higress.cn/zh-cn/docs/user/quickstart)”文档中“场景二：在本地 K8s 环境中使用”里使用的命令为例。其原始内容如下：

```bash
helm install higress -n higress-system higress.io/higress --create-namespace --render-subchart-notes --set global.local=true --set higress-console.o11y.enabled=false
```

如果要补充 `higress-core.gateway.hostNetwork true` 这个参数的话，那命令应改为：

```bash
helm install higress -n higress-system higress.io/higress --create-namespace --render-subchart-notes --set global.local=true --set higress-console.o11y.enabled=false --set higress-core.gateway.hostNetwork=true
```
